### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Jarrodsz** [austenc/tauri-bug-accept-first-mouse-macos#1]
Did you ever find a solution?

in my case a window loaded from tray with react always needs 2 clicks.

so for example if i have a settings window and ick an inlut on it needs 2 clicks makes it unshippable

**Comment by austenc** [comment]
No easy fix for this yet. Focus states are tricky. Electron has similar issues in some cases too. I made this repo to make it easy for the Tauri maintainers to reproduce and isolate the bug. Unfortunately I'm too much of a Rust noob still to figure it out. 

There may be some workarounds using janky hacks like `setTimeout`, but they're not 100% effective. Hoping it gets fixed, but that's about all I can do at this point! 🙏

**Comment by Jarrodsz** [comment]
I switched to flutter
I was so sick of these issues spend days debugging thank you.

Rust is also a total waste pf time
Imo. Never again. Im redoing my app in flutter totally

**Comment by austenc** [comment]
Sorry to hear you’ve had a bad time with Tauri. This issue isn’t adding much useful information to a repo made for the sole purpose of showing a minimal reproduction of the bug so I’m going to close it. Thank you!
